# Generated by Django 5.0.4 on 2024-05-18 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0002_musician_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='musician',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
