# Generated by Django 5.0.4 on 2024-05-18 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0003_alter_musician_age_alter_musician_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='salary',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
